---
# tasks file for user_creation
- include_vars: users.yml

- name: create user with home directory
  user: name={{ item.username }} shell=/bin/bash groups=wheel createhome=yes comment='by ansible'
  with_items: '{{users}}'

- name: Setup |authorized key upload
  authorized_key: user={{ item.user }}
                  key="{{ lookup('file', files/{{ item.username }}.pub)}}"
  when: '{{ item-use_sudo }} == True'
  with_items: '{{users}}'

